[WDP230901-8] added color variables
matwjablonski/wdp-2309-01 pull request #10
Opened 2023-09-08 20:22 UTC by karollion

https://projects.kodilla.com/browse/WDP230901-8

- dodałem zmienne dla kolorów 
- dodałem zmienne do używania w projekcie i przypisałem do nich zmienne kolorów 
- zastosowałem zmienne kolorów w projekcie

Proszę nie używać zmiennych kolorów w projekcje, mogą być one wykorzystane jedynie w settings.scss.
Do kolorowania w projekcie służą zmienne oznaczone PROJECT COLOR VARIABLES

2023-09-09 09:54 UTC, Justek9 requested changes
W pliku ProductSearch.module.scss znaczniki select i button mają background-color, który nie jest zmienną. Reszta super!

2023-09-09 10:46 UTC, karollion commented
> W pliku ProductSearch.module.scss znaczniki select i button mają background-color, który nie jest zmienną. Reszta super!

Poprawione

2023-09-09 10:49 UTC, Justek9 approved these changes

2023-09-09 12:26 UTC, wierza approved these changes
Po zmianach zaproponowanych przez Justynę jest ok. Choć sprawdzanie to jak tropienie mordercy u Agaty Christie  ;)

2023-09-09 17:29 UTC, Viktoryia-Vysotskaya submitted a review, later dismissed

2023-09-11 10:30 UTC, matwjablonski requested changes
konflikty

2023-09-11 18:47 UTC, Justek9 approved these changes

2023-09-11 21:42 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-11 21:42 UTC, Viktoryia-Vysotskaya commented
Oki

2023-09-12 06:57 UTC, merged