WDP230901-3-add hover state of feature boxes
matwjablonski/wdp-2309-01 pull request #11
Opened 2023-09-09 04:58 UTC by Justek9

https://projects.kodilla.com/browse/WDP230901-3

-dodałam hover dla każdego z feature boxów
-zmieniłam feature boxy z div na linki

2023-09-09 09:04 UTC, karollion submitted a review, later dismissed
Hover działa na każdym elemencie, dobra robota

2023-09-09 13:49 UTC, wierza approved these changes
Za radą Karola ściągnąłem brancha i hovery hulają aż miło ;)

2023-09-09 17:29 UTC, Viktoryia-Vysotskaya submitted a review, later dismissed

2023-09-11 10:33 UTC, matwjablonski requested changes
zmieniałaś jakieś pakiety? jeśli nic nie zmieniałaś to yarn.lock nie powinien się tu znaleźć.

2023-09-11 10:37 UTC, Justek9 commented
> zmieniałaś jakieś pakiety? jeśli nic nie zmieniałaś to yarn.lock nie powinien się tu znaleźć.

Nie zmieniałam, a wręcz innym też zalecałam nie zmienianie. Zrobić to od zadanie nowa czy usunąć node modules i zainstalować jeszcze raz?

2023-09-11 11:38 UTC, Justek9 commented
> zmieniałaś jakieś pakiety? jeśli nic nie zmieniałaś to yarn.lock nie powinien się tu znaleźć.

zgodnie ze wskazówką wyrzuciłam yarn.lock lokalnie i wzięłam go z głównego brancha

2023-09-11 11:57 UTC, matwjablonski requested changes

2023-09-11 11:57 UTC, matwjablonski commented on src/components/common/FeatureBox/FeatureBox.module.scss
> -  &.active {
ok, jeszcze mam pytanie o klasę active, bo tutaj ją usuwasz, ale zostawiłaś całą logikę jej dotyczącą w kodzie JS

2023-09-11 12:08 UTC, Justek9 commented on src/components/common/FeatureBox/FeatureBox.module.scss
> -  &.active {
> ok, jeszcze mam pytanie o klasę active, bo tutaj ją usuwasz, ale zostawiłaś całą logikę jej dotyczącą w kodzie JS

Słusznie, moje przeoczenie, naprawione

2023-09-11 17:21 UTC, karollion approved these changes
Wszystko oki

2023-09-11 21:45 UTC, Viktoryia-Vysotskaya commented
Oki)

2023-09-11 21:45 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-12 06:58 UTC, matwjablonski approved these changes

2023-09-12 06:58 UTC, merged