Add styles and active states
matwjablonski/wdp-2309-01 pull request #12
Opened 2023-09-09 11:57 UTC by wierza

https://projects.kodilla.com/browse/WDP230901-5

- dodałem margines między przyciskami
- niektóre przyciski wyświetlają się jako aktywne po wejściu na home

2023-09-09 17:30 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-09 17:31 UTC, Justek9 reviewed
W związku z tym, że w scss są właściwości color i background-color proponuję poczekać najpierw na merge pull request Karola, w którym definiuje zmienne dla kolorów i od razu w tym zadaniu używać zmiennych :)

2023-09-09 17:46 UTC, karollion requested changes
Pliki .zshrc oraz yarn.lock nie są potrzebne do tego zadania.

reszta chyba ok tylko kolory będzie trzeba zmienić jak już pull request z nimi wejdzie do maina

2023-09-09 18:34 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-11 18:05 UTC, karollion submitted a review, later dismissed
Po usunięciu yarn.lock jest dobrze

2023-09-11 21:47 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-14 18:00 UTC, karollion submitted a review, later dismissed

2023-09-14 19:53 UTC, Viktoryia-Vysotskaya commented
Działo)

2023-09-14 19:53 UTC, Viktoryia-Vysotskaya submitted a review, later dismissed

2023-09-15 07:12 UTC, Justek9 approved these changes

2023-09-15 07:26 UTC, matwjablonski commented
Dlaczego cały yarn.lock jest usunięty z projektu? Chodziło o usunięcie go tylko z PR. Przywróć lokalnie wersję z main'a do swojego brancha i będzie ok :)

2023-09-15 17:19 UTC, wierza commented
> Dlaczego cały yarn.lock jest usunięty z projektu? Chodziło o usunięcie go tylko z PR. Przywróć lokalnie wersję z main'a do swojego brancha i będzie ok :)

Zrobione

2023-09-15 17:21 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-15 17:21 UTC, Justek9 approved these changes

2023-09-15 17:56 UTC, karollion approved these changes

2023-09-15 18:05 UTC, merged