Add styles on select
matwjablonski/wdp-2309-01 pull request #13
Opened 2023-09-09 13:25 UTC by wierza

https://projects.kodilla.com/browse/WDP230901-7

- pomniejszyłem czcionkę
- usunąłem outline
- dodałem hover na category

2023-09-09 17:31 UTC, Viktoryia-Vysotskaya submitted a review, later dismissed

2023-09-09 17:37 UTC, karollion approved these changes
Wygląda dobrze

2023-09-11 10:36 UTC, matwjablonski requested changes

2023-09-11 10:36 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +        color: white;
nie używajmy kolorów w formie nazwanej, poproszę zmienną / lub hex / lub rgb

2023-09-11 10:36 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +
ta pusta linia do usunięcia

2023-09-11 10:36 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +      .icon:first-child {
wg reszty plików pomiędzy regułami jest wolna linia wszędzie, tutaj jest ciągiem - podobnie w linii 17 (dla select) i niżej

2023-09-11 16:15 UTC, wierza commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +
Usunąłem.

2023-09-11 17:35 UTC, karollion submitted a review, later dismissed
Jest spoko

2023-09-11 19:35 UTC, Justek9 submitted a review, later dismissed

2023-09-11 21:48 UTC, Viktoryia-Vysotskaya commented
Oki)

2023-09-11 21:49 UTC, Viktoryia-Vysotskaya submitted a review, later dismissed

2023-09-12 07:00 UTC, matwjablonski requested changes

2023-09-12 07:00 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +        color: #ffffff;
kolory są już zmergowane, więc możesz zastąpić od razu kolory zmiennymi

2023-09-15 19:48 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-15 20:17 UTC, karollion reviewed
Dodaj proszę animacje do hover  ( @extend %transitionHover; )

2023-09-15 20:45 UTC, wierza commented
> Dodaj proszę animacje do hover ( @extend %transitionHover; )

Dodałem

2023-09-15 20:49 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-15 20:59 UTC, karollion approved these changes
Działa 👍

2023-09-17 08:38 UTC, merged