WDP230901-1-Add-images-for-the-project
matwjablonski/wdp-2309-01 pull request #14
Opened 2023-09-09 19:30 UTC by Viktoryia-Vysotskaya

https://projects.kodilla.com/browse/WDP230901-1

- Dodałem zdjęcia na stronę główną.
- Wrzuciłam także zdjęcia pozostałych sekcji stron, które będą w projekcie, zgodnie z plikami.

2023-09-09 20:14 UTC, karollion submitted a review, later dismissed
Wygląda spoko zdjęcia są choć nie wiem czemu zmieniałaś też price i stars ale ok zatwierdzam

2023-09-09 20:28 UTC, Viktoryia-Vysotskaya commented
> Wygląda spoko zdjęcia są choć nie wiem czemu zmieniałaś też price i stars ale ok zatwierdzam

Dziękuję) Zmieniłam price i stars, żeby projekt nie był nudny))

2023-09-09 20:39 UTC, Justek9 reviewed
Hej, moim zdaniem powinniśmy trzymać się ustaleń ,że zmieniamy tylko to, czego dotyczy task. Projekt nie będzie nudny jak zrobimy zadania :)

2023-09-09 20:42 UTC, Viktoryia-Vysotskaya commented
> Hej, moim zdaniem powinniśmy trzymać się ustaleń ,że zmieniamy tylko to, czego dotyczy task. Projekt nie będzie nudny jak zrobimy zadania :)

Dobrze. Teraz naprawię.

2023-09-09 20:57 UTC, Viktoryia-Vysotskaya commented
> Hej, moim zdaniem powinniśmy trzymać się ustaleń ,że zmieniamy tylko to, czego dotyczy task. Projekt nie będzie nudny jak zrobimy zadania :)

Już jest)

2023-09-10 07:01 UTC, Justek9 approved these changes
super :)

2023-09-10 07:12 UTC, karollion submitted a review, later dismissed
ok

2023-09-11 10:40 UTC, matwjablonski requested changes

2023-09-11 10:40 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +      <img className={styles.image} src={image} alt='furniture' />
ten alt jest zbyt ogólny, mamy name w propsach użyjmy go :)

2023-09-11 10:40 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.module.scss
> +      margin: 10px 10px;
wystarczy jeden raz 10px

2023-09-11 21:12 UTC, Viktoryia-Vysotskaya commented on src/components/common/ProductBox/ProductBox.js
> +      <img className={styles.image} src={image} alt='furniture' />
Done )

2023-09-11 21:12 UTC, Viktoryia-Vysotskaya commented on src/components/common/ProductBox/ProductBox.module.scss
> +      margin: 10px 10px;
Done)

2023-09-11 21:30 UTC, Viktoryia-Vysotskaya commented
> Na dole wyświetlają się konflikty

Done)

2023-09-12 04:38 UTC, karollion approved these changes

2023-09-12 07:01 UTC, matwjablonski approved these changes

2023-09-12 07:01 UTC, merged