WDP230901-10_add-menu-with-category-list
matwjablonski/wdp-2309-01 pull request #16
Opened 2023-09-10 19:26 UTC by wierza

https://projects.kodilla.com/browse/WDP230901-10

- dodałem menu z listą kategorii w formie linków, które wyświetla się po najechaniu kursorem na "select category"

2023-09-11 22:02 UTC, Viktoryia-Vysotskaya commented
- Może warto sprawić, by kolor starej ceny był bardziej zauważalny – na przykład czerwony? 
- I zwiększyć liczbę produktów, w przeciwnym razie z 24 produktów tylko 2 mają starą cenę?
- A tak - wszystko działo)))

2023-09-11 22:11 UTC, Viktoryia-Vysotskaya commented
Widzę to menu - wszystko działa)

2023-09-12 07:04 UTC, matwjablonski requested changes

2023-09-12 07:04 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +        color: #ffffff;
kolory ze zmiennych 

ten kod widziałem w innym PR. na pewno zrobiłeś brancha od main'a?

2023-09-12 07:04 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +      border: 1px solid #ccc;
jak wyżej, kolory ze zmiennych poproszę

2023-09-15 19:57 UTC, Viktoryia-Vysotskaya commented
- ./src/components/features/ProductSearch/ProductSearch.module.scss - linejka _131_ -  **Expected '}'**.

2023-09-15 20:46 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-15 20:54 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-16 19:03 UTC, karollion reviewed
![5151](https://github.com/matwjablonski/wdp-2309-01/assets/128591081/a2b18e43-9e22-467d-9178-05b383e66888)

wszystko działa dobrze,  jak byś mógł tylko zrobić żeby ta ramka na dole nie przenikała przez menu i żeby miało szerokość tego "select a category" i dodac animacje do hover

2023-09-17 08:32 UTC, wierza commented
> ![5151](https://user-images.githubusercontent.com/128591081/268466540-a2b18e43-9e22-467d-9178-05b383e66888.png)
> 
> wszystko działa dobrze, jak byś mógł tylko zrobić żeby ta ramka na dole nie przenikała przez menu i żeby miało szerokość tego "select a category" i dodac animacje do hover

Zrobiłem.

2023-09-17 09:30 UTC, Viktoryia-Vysotskaya commented
> > ![5151](https://user-images.githubusercontent.com/128591081/268466540-a2b18e43-9e22-467d-9178-05b383e66888.png)
> > wszystko działa dobrze, jak byś mógł tylko zrobić żeby ta ramka na dole nie przenikała przez menu i żeby miało szerokość tego "select a category" i dodac animacje do hover
> 
> Zrobiłem.

- Ale nie do końca - wysokość tego bloku 'Select' trzeba zmienić, o to jescze chodzi , żeby nie nachodził na block 'Free Shipping'.

![image](https://github.com/matwjablonski/wdp-2309-01/assets/128961439/17b82d78-5928-48f4-aa0d-e9ed36bd43d0)

2023-09-17 12:11 UTC, karollion reviewed
dodaj jeszcze animacje na hovery i bedzie perfecto

2023-09-17 12:31 UTC, karollion approved these changes

2023-09-17 13:03 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-18 05:53 UTC, merged