Bugfix/wdp230901 6 add old price
matwjablonski/wdp-2309-01 pull request #17
Opened 2023-09-11 16:56 UTC by Justek9

https://projects.kodilla.com/browse/WDP230901-6

- dodałam "oldPrice" dla część produktów w initialState
- ostylowałam je przekreśleniem i kolorem szarym

2023-09-11 17:30 UTC, karollion approved these changes
Wygląda oki

2023-09-11 20:41 UTC, karollion approved these changes

2023-09-11 22:03 UTC, Viktoryia-Vysotskaya commented
- Może warto sprawić, by kolor starej ceny był bardziej zauważalny – na przykład czerwony?
- I zwiększyć liczbę produktów, w przeciwnym razie z 24 produktów tylko 2 mają starą cenę?
- A tak - wszystko działo)))

2023-09-12 07:04 UTC, matwjablonski approved these changes

2023-09-12 19:10 UTC, karollion requested changes

2023-09-12 19:18 UTC, Justek9 commented on src/styles/settings.scss
W tym momencie plik settings.scss wygląda idealnie tak, jak Ty go stworzyłeś. W tym czerwonym fragmencie usuwałam kod, który tam był przed wprowadzeniem Twoich zmian i który był w konflikcie z Twoimi ( $text-color: #2a2a2a;
$text-color-old-price: #b6b6b6;)

2023-09-12 19:24 UTC, closed without merging