Feature/wdp230901 11 add to favourite button
matwjablonski/wdp-2309-01 pull request #19
Opened 2023-09-12 09:04 UTC by Justek9

https://projects.kodilla.com/browse/WDP230901-11

- dodałam dla produktów isFavourite w initialState
- te zaznaczone jako "true" mają kolor kremowy
- można togglować isFavorite po naciśnięciu guzika z serduszkiem
- zaktualizowałm test tego komponentu, opakowując go w Provider i przekazując do niego store

2023-09-12 19:09 UTC, karollion requested changes

2023-09-12 19:09 UTC, karollion commented on src/styles/settings.scss
Nie usuwaj tego komentarza

2023-09-12 19:39 UTC, matwjablonski commented on src/styles/settings.scss
dlaczego nie?

2023-09-12 20:10 UTC, karollion commented on src/styles/settings.scss
W zadaniu z zmiennymi kolorów było napisane żeby rozdzielić listę kolorów dla zmiennych z zmiennymi kolorów

2023-09-13 17:11 UTC, karollion approved these changes

2023-09-13 19:57 UTC, closed without merging