[WDP230901-15] added RWD topbar and baner
matwjablonski/wdp-2309-01 pull request #22
Opened 2023-09-12 17:15 UTC by karollion

https://projects.kodilla.com/browse/WDP230901-15

- dodałem RWD zgodnie z poleceniem w zadaniu do topbar
- dodałem RWD zgodnie z poleceniem w zadaniu do banner

2023-09-12 22:14 UTC, Justek9 reviewed
responsywność pięknie działa, zgodnie założeniami z zadania, zastanawiały mnie jedynie puste spacje {' '} w niektórych miejscach w CompanyClaim.js i TopBar.js i zastosowanie transform: translate(0, 0) przy klasie cart i phone number w media queries

2023-09-13 16:30 UTC, Justek9 submitted a review, later dismissed
super :)

2023-09-13 17:12 UTC, matwjablonski approved these changes

2023-09-13 17:14 UTC, matwjablonski requested changes
sprawdź rozdzielczość 320px bo dropdowny po lewej mają bardzo duże przerwy pomiędzy - warto pomyśleć o zmniejszeniu przerw

2023-09-14 06:42 UTC, Justek9 approved these changes

2023-09-14 17:52 UTC, wierza approved these changes
U mnie wszystko działa.

2023-09-14 20:34 UTC, Viktoryia-Vysotskaya commented
Nie wiem jak to dokładnie powinno wyglądać, na jakej ilości tych rozdzielczośći , ale 
- na rozdzielczośći 320-353px logo naplywa na ikonę z numerom telefona (może zmniejszyć ikonę i ten numer) .  
- z 420px - już nie widać części ikonę menu, koszyka i numeru telefonu.

2023-09-15 13:50 UTC, Viktoryia-Vysotskaya commented
Super) Wszystko działo)

2023-09-15 13:50 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-15 16:21 UTC, Justek9 approved these changes

2023-09-15 18:10 UTC, matwjablonski approved these changes

2023-09-15 18:10 UTC, merged