WDP230901-16_Add RDW on FeatureBoxes
matwjablonski/wdp-2309-01 pull request #24
Opened 2023-09-13 18:16 UTC by wierza

https://projects.kodilla.com/browse/WDP230901-16

- dodałem RDW  do FeaturesBox, aby wyświetlały się po dwie karty w dwóch rzędach i aby wysokości kart były równe.

2023-09-14 07:19 UTC, Justek9 requested changes
Myślę, że wrsje tablet i mobile są ok, ale boxy w wersji desktop miały być niezmienione (4 w rzędzie), dopiero od tabletu po 2 w rzędzie, a teraz od razu w wersji desktop są 2 w rzędzie

2023-09-14 19:09 UTC, wierza commented
> Myślę, że wrsje tablet i mobile są ok, ale boxy w wersji desktop miały być niezmienione (4 w rzędzie), dopiero od tabletu po 2 w rzędzie, a teraz od razu w wersji desktop są 2 w rzędzie

Dzięki! Poprawiłem.

2023-09-14 21:33 UTC, Viktoryia-Vysotskaya commented
- Rozszerzenie 320-330 px - trzy rzędy (1 blok, 1 blok, 2 bloki)
- Rozszerzenie 331-344 px - trzy rzędy (1 blok, 2 bloki, 1 blok)
- Rozszerzenie 769-991px - trzeci blok ("Money Back") ma mniejszą wysokość niż pozostałe

2023-09-14 21:38 UTC, Viktoryia-Vysotskaya commented
Dlaczego nie dodasz w pliku src/components/common/FeatureBox/FeatureBox.module.scss zmian? Np.,

```scss
@media (max-width: 991px) {
  .root {
    height: 75%;
  }
}

@media (max-width: 300px) {
  h5 {
    font-size: 18px;
  }

  p {
    font-size: 14px;
  }
}
``` 
Coś takiego?

2023-09-14 21:48 UTC, Viktoryia-Vysotskaya commented
- Dodałam kilka zmian jako opcję (jak ja widzę). Spójrz, może wynik będzie dokładniejszy, tak dla pewności)

2023-09-15 17:58 UTC, Justek9 approved these changes

2023-09-15 19:05 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-16 19:25 UTC, karollion approved these changes
Działa super :)

2023-09-17 08:40 UTC, matwjablonski approved these changes

2023-09-17 08:40 UTC, merged