WDP2309-11 add to favourite funcionality
matwjablonski/wdp-2309-01 pull request #25
Opened 2023-09-13 19:58 UTC by Justek9

https://projects.kodilla.com/browse/WDP230901-11

-dodałam dla produktów isFavourite w initialState
-te zaznaczone jako "true" mają kolor kremowy
-można togglować isFavorite po naciśnięciu guzika z serduszkiem
-zaktualizowałm test tego komponentu, opakowując go w Provider i przekazując do niego store

2023-09-13 20:23 UTC, karollion approved these changes
Wyglada oki

2023-09-14 18:17 UTC, wierza requested changes
Będą znowu konflikty, bo w tym moim ja dodałem nie isFavorite tylko Favorite.

2023-09-14 18:20 UTC, Justek9 commented
> Będą znowu konflikty, bo w tym moim ja dodałem nie isFavorite tylko Favorite.

Nie mogłam już dłużej czekać, chciałam zacząć nowe zadanie, jak pojawią się konflikty , postaram się je rozwiązać. Niestety przy obecnym tempie zatwierdzania nie mogę czekać, aż poprzednie zadania będą zmergowane

2023-09-14 18:22 UTC, Justek9 commented
> Będą znowu konflikty, bo w tym moim ja dodałem nie isFavorite tylko Favorite.

Jeżeli innych niezgodności nie widzisz to proszę o accept

2023-09-14 22:37 UTC, Viktoryia-Vysotskaya commented
Działo)

2023-09-14 22:37 UTC, Viktoryia-Vysotskaya submitted a review, later dismissed

2023-09-15 16:40 UTC, wierza submitted a review, later dismissed

2023-09-16 19:28 UTC, karollion submitted a review, later dismissed
Działa dobrze :)

2023-09-16 19:37 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-17 13:05 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-17 13:13 UTC, karollion approved these changes

2023-09-17 20:04 UTC, wierza approved these changes
Serduszka działają ;)

2023-09-18 05:55 UTC, merged