WDP230901-12-Compare-products
matwjablonski/wdp-2309-01 pull request #28
Opened 2023-09-14 19:43 UTC by Viktoryia-Vysotskaya

https://projects.kodilla.com/browse/WDP230901-12

- Dodałam możliwość wyboru produktów do porównania.
- StickyBar.
-  Ikona zamykania, usuwanie  produktów z porównania.

2023-09-15 11:23 UTC, Justek9 requested changes
Ładny komponent Ci wyszedł :) jedno małe "ale": po kliknięciu guzik przy produkcie dodanym do porównania nie zmienia koloru

2023-09-15 11:29 UTC, Viktoryia-Vysotskaya commented
> Ładny komponent Ci wyszedł :) jedno małe "ale": po kliknięciu guzik przy produkcie dodanym do porównania nie zmienia koloru

Dziękuję)) Ale w zadaniu napisano, ze "mają mieć ten guzik zawsze taki jak na hover (kremowy)", tzn - kolor zawsze kremowy. Czy nie o to chodzi?

2023-09-15 11:31 UTC, Viktoryia-Vysotskaya commented
> > Ładny komponent Ci wyszedł :) jedno małe "ale": po kliknięciu guzik przy produkcie dodanym do porównania nie zmienia koloru
> 
> Dziękuję)) Ale w zadaniu napisano, ze "mają mieć ten guzik zawsze taki jak na hover (kremowy)", tzn - kolor zawsze kremowy. Czy nie o to chodzi? Czy to o ten guzik porównania? Już się pogubiłam))))

2023-09-15 11:31 UTC, Viktoryia-Vysotskaya commented
> > Ładny komponent Ci wyszedł :) jedno małe "ale": po kliknięciu guzik przy produkcie dodanym do porównania nie zmienia koloru
> 
> Dziękuję)) Zrobię)

2023-09-15 11:32 UTC, Viktoryia-Vysotskaya commented
> Ładny komponent Ci wyszedł :) jedno małe "ale": po kliknięciu guzik przy produkcie dodanym do porównania nie zmienia koloru

Dziękuję)) Zrobię)

2023-09-15 15:12 UTC, Viktoryia-Vysotskaya commented
> Ładny komponent Ci wyszedł :) jedno małe "ale": po kliknięciu guzik przy produkcie dodanym do porównania nie zmienia koloru

Done)

2023-09-15 16:21 UTC, Justek9 approved these changes

2023-09-15 21:14 UTC, karollion reviewed
Dodaj proszę animacje do hovera na buttonie compare

2023-09-16 19:30 UTC, karollion submitted a review, later dismissed
Działa prawidłowo, animacja jest 👍

2023-09-17 17:26 UTC, karollion approved these changes

2023-09-17 20:02 UTC, wierza approved these changes
Porównywanie działa. 5 produktu nie można dodać.

2023-09-18 08:19 UTC, Justek9 approved these changes

2023-09-18 08:36 UTC, merged