(WDP230901-27-Gallery-section-component
matwjablonski/wdp-2309-01 pull request #30
Opened 2023-09-15 14:52 UTC by Viktoryia-Vysotskaya

https://projects.kodilla.com/browse/WDP230901-27

- Dodałam sekcję "Galeria".

2023-09-15 20:18 UTC, wierza approved these changes

2023-09-16 07:37 UTC, karollion reviewed
Wyglada spoczko, ale dodał bym animacje do wszystkich hoverów a w tych czarnych przyciskach na dole zmienił bym hover zeby tło sie zmieniało na pomaranczowy a nie strzałeczka tak jak w sekcji promoted wg layoutu z zadania
https://uploads.kodilla.com/bootcamp/wdp/group-project-01/section-featured.png

2023-09-16 07:57 UTC, Viktoryia-Vysotskaya commented
> Wyglada spoczko, ale dodał bym animacje do wszystkich hoverów a w tych czarnych przyciskach na dole zmienił bym hover zeby tło sie zmieniało na pomaranczowy a nie strzałeczka tak jak w sekcji promoted wg layoutu z zadania https://uploads.kodilla.com/bootcamp/wdp/group-project-01/section-featured.png

- Mam swoje zadanie i swój link https://uploads.kodilla.com/bootcamp/wdp/group-project-01/section-gallery.png
Tam hover na strzałkach, a nie na tłie.
-Animację dodam na hover.

2023-09-16 09:40 UTC, Justek9 requested changes
W zadaniu jest mowa o pobieraniu treści ze stanu aplikacji, a Ty je wrzucasz na sztywno, na lewym zdjeciu na przykład cenę, starą cenę, nazwę spokojnie można brać ze stanu

2023-09-16 16:06 UTC, Viktoryia-Vysotskaya commented
> W zadaniu jest mowa o pobieraniu treści ze stanu aplikacji, a Ty je wrzucasz na sztywno, na lewym zdjeciu na przykład cenę, starą cenę, nazwę spokojnie można brać ze stanu

2023-09-16 16:15 UTC, Viktoryia-Vysotskaya commented
> W zadaniu jest mowa o pobieraniu treści ze stanu aplikacji, a Ty je wrzucasz na sztywno, na lewym zdjeciu na przykład cenę, starą cenę, nazwę spokojnie można brać ze stanu

-U mnie tam stoji zdj 15,np., które jest w 'images', ale nie ma go w 'initialState.js'. Nie rozumiem -  jak mam zrobić: dodać product do 'initialState', czyli zdj tyłko tam zmienić, czy jak? Jak będzie ta nazwa, cena pobierana - w zalezności od numeru zdj? 
- Treśc ze stanu aplikacji - to moze znaczyć 'hover', 'kolor', 'ikonki'.  
-Będzie czas - napisz do mnie na czacie, bo nie mam pojęcia, jak to zmienić trzeba.

2023-09-17 20:21 UTC, wierza submitted a review, later dismissed
Viktoria, ja dziś w zadaniu 19 dodałem wszystkie produkty. Jeśli je Mateusz zmerguje szybko to wtedy możesz pobierać je ze stanu. To jest zadanie 27 i zakłada że produkt ze zdjęciem 15 już jest w stanie, bo  w 19 zadaniu było dodawanie produktów.

2023-09-17 20:46 UTC, Viktoryia-Vysotskaya commented
> Viktoria, ja dziś w zadaniu 19 dodałem wszystkie produkty. Jeśli je Mateusz zmerguje szybko to wtedy możesz pobierać je ze stanu. To jest zadanie 27 i zakłada że produkt ze zdjęciem 15 już jest w stanie, bo w 19 zadaniu było dodawanie produktów.

Spoko) Dla mnie glównie, zeby działało, a nie jakie zdj)

2023-09-18 16:25 UTC, wierza submitted a review, later dismissed

2023-09-18 18:00 UTC, Justek9 submitted a review, later dismissed

2023-09-18 19:11 UTC, karollion submitted a review, later dismissed

2023-09-18 19:51 UTC, wierza approved these changes

2023-09-18 20:25 UTC, wierza approved these changes

2023-09-18 20:29 UTC, Justek9 approved these changes

2023-09-18 20:30 UTC, wierza approved these changes

2023-09-19 08:16 UTC, merged