WDP230901-13-Swipeable-swipe-support
matwjablonski/wdp-2309-01 pull request #33
Opened 2023-09-15 23:25 UTC by Viktoryia-Vysotskaya

https://projects.kodilla.com/browse/WDP230901-13

- Dodałam Swiper.
- Zwrapowałam całą zawartość NewFurniture w Swipeable.

2023-09-16 07:32 UTC, karollion reviewed
Działa ale czemu tyle rzeczy zmieniasz w package.json

- zamiast tych strzałek bocznych mogłabys zrobic takie na dole jak sa w sekcji promoted bo te to w ogole wystają poza container strony
- czemu jak sie klika w przycisk to to tak wyrzuca na góre strony?

2023-09-16 07:52 UTC, Viktoryia-Vysotskaya commented
> Działa ale czemu tyle rzeczy zmieniasz w package.json
> 
> * zamiast tych strzałek bocznych mogłabys zrobic takie na dole jak sa w sekcji promoted bo te to w ogole wystają poza container strony
> * czemu jak sie klika w przycisk to to tak wyrzuca na góre strony?


- Zainstalowane odrazu tylko te programy, które są potrzebne dla Swiper. 
- Wersji innych programm - zaktualizowane, bo na tych co w początkowym package.json Swiper nie działa, przynajmniej na moim laptopie.
- Z pytaniem o górę strony - to nie wiem, nigdzie nie mogłam znaleźć żadnych informacji na ten temat. Jeśli znajdę dziś - to dodam.
- W zadaniu nie napisano, jakie konkretne strzałki powinny być. A gdzie oni wystają poza container strony? Moze nie tak sprawdzam? 

![image](https://github.com/matwjablonski/wdp-2309-01/assets/128961439/c247af98-88c9-4092-aa4a-f6d7a310b6c4)

2023-09-16 19:15 UTC, karollion reviewed
![5151](https://github.com/matwjablonski/wdp-2309-01/assets/128591081/034e2aa1-4129-4a0b-8e55-d20fe77335ca)
 strzałki nadal poza obrysem layoutu

2023-09-17 10:36 UTC, karollion requested changes
Mogła byś zrobić tak żeby w NewFeature zrobić te strzałki i przekazywać je jako propsy do Swipable? Wtedy można by użyć Swipable w innych miejscach gdzie strzałki wygladają inaczej i sa w innych miejscach

2023-09-18 15:24 UTC, karollion approved these changes

2023-09-18 15:26 UTC, karollion reviewed
A co tu sie stało z kartami produktów że same zdjęcia są?

2023-09-18 15:51 UTC, Viktoryia-Vysotskaya commented
> A co tu sie stało z kartami produktów że same zdjęcia są?

Tylko to chyba nie u mnie, bo nawet nie robiłam zmian w ProductBox.

2023-09-18 16:26 UTC, karollion commented on src/components/common/ProductBox/ProductBox.js
nadal coś nie tak z produkc boxami, czemu je zmieniasz?

2023-09-18 16:36 UTC, Viktoryia-Vysotskaya commented on src/components/common/ProductBox/ProductBox.js
Co nie tak? Wszystko jak w designie - muszą być na zdj i mieć hover na visibility.

2023-09-18 17:42 UTC, wierza approved these changes

2023-09-18 20:26 UTC, wierza submitted a review, later dismissed

2023-09-19 04:30 UTC, karollion submitted a review, later dismissed

2023-09-19 14:19 UTC, karollion approved these changes

2023-09-19 15:29 UTC, Justek9 approved these changes

2023-09-19 17:25 UTC, merged