WDP230901-31 Add functionality to Brands section
matwjablonski/wdp-2309-01 pull request #41
Opened 2023-09-19 19:16 UTC by wierza

https://projects.kodilla.com/browse/WDP230901-31

- dodałem przesuwanie marek w sliderze, w zależności od wielkości ekranu

2023-09-19 19:47 UTC, Justek9 requested changes
Zmiana marek działa poprawnie, ale myślę, że warto dać im większą szerokość na tabletach i tel, teraz są bardzo ściśnięte
![brands](https://github.com/matwjablonski/wdp-2309-01/assets/108572018/f5aa8d29-b56f-4de2-b02a-36ffa760d7e1)

2023-09-19 19:52 UTC, wierza commented
> Zmiana marek działa poprawnie, ale myślę, że warto dać im większą szerokość na tabletach i tel, teraz są bardzo ściśnięte ![brands](https://user-images.githubusercontent.com/108572018/269076788-f5aa8d29-b56f-4de2-b02a-36ffa760d7e1.jpg)

Ale to jest kolejne zadanie Viktorii RWD. Tu chodziło tylko o funkcjonalność.

2023-09-19 19:55 UTC, Justek9 approved these changes

2023-09-19 19:56 UTC, Justek9 commented
> > Zmiana marek działa poprawnie, ale myślę, że warto dać im większą szerokość na tabletach i tel, teraz są bardzo ściśnięte ![brands](https://user-images.githubusercontent.com/108572018/269076788-f5aa8d29-b56f-4de2-b02a-36ffa760d7e1.jpg)
> 
> Ale to jest kolejne zadanie Viktorii RWD. Tu chodziło tylko o funkcjonalność.

Ok

2023-09-19 21:01 UTC, karollion approved these changes

2023-09-20 05:38 UTC, matwjablonski approved these changes

2023-09-20 05:38 UTC, merged