Feature/WDP230901 34 component feedback functionality
matwjablonski/wdp-2309-01 pull request #42
Opened 2023-09-19 19:57 UTC by karollion

https://projects.kodilla.com/browse/WDP230901-34

- zrobiłem funkcje do przesuwania w lewo i prawo
- dodałem Swipable

2023-09-19 22:26 UTC, Justek9 requested changes

2023-09-19 22:26 UTC, Justek9 commented on src/components/features/Feedback/Feedback.js
>        <li>
brakuje "key"

2023-09-20 05:37 UTC, matwjablonski requested changes

2023-09-20 05:37 UTC, matwjablonski commented on src/components/features/Feedback/Feedback.js
> +          onClick={() => handleCommentChange(i)}
brakuje preventDefault

2023-09-20 05:37 UTC, matwjablonski commented on src/components/features/Feedback/Feedback.module.scss
> +    }
coś nie równo :)

2023-09-20 17:35 UTC, closed without merging