Feature/WDP230901 24 section Promoted RWD
matwjablonski/wdp-2309-01 pull request #45
Opened 2023-09-20 16:59 UTC by karollion

https://projects.kodilla.com/browse/WDP230901-24

dodałem swipable i funkcje do strzałem
zrobiłem RWD

2023-09-20 18:36 UTC, Justek9 requested changes
Napiszę Ci analogiczną uwagę, którą wczoraj Mateusz mi dał do komponentu Sale: obsłuż sytuację, że żaden produkt nie jest na promocji (wszystkie mają promoted:false), teraz to wysypuje stronę

2023-09-20 19:03 UTC, matwjablonski requested changes

2023-09-20 19:03 UTC, matwjablonski commented on src/components/features/Promoted/Promoted.js
> +  const [activeProduct1, setActiveProduct1] = useState(9);
co znaczy 9?

2023-09-20 19:03 UTC, matwjablonski commented on src/components/features/Promoted/Promoted.js
> +import Swipeable from '../../common/Swipeable/Swipeable.js';
rozszerzenie jest chyba zbędne tutaj

2023-09-20 19:03 UTC, matwjablonski commented on src/components/features/Promoted/Promoted.js
> +      setFade2(false);
fade i fade2 są kiepskimi nazwami, jeśli masz dwa fade'y i chcesz je rozróżnić - nadaj im bardziej opisowe nazwy

2023-09-20 20:45 UTC, karollion commented on src/components/features/Promoted/Promoted.js
> +      setFade2(false);
Poprawione

2023-09-20 20:45 UTC, karollion commented on src/components/features/Promoted/Promoted.js
> +import Swipeable from '../../common/Swipeable/Swipeable.js';
Poprawione

2023-09-20 20:45 UTC, karollion commented on src/components/features/Promoted/Promoted.js
> +  const [activeProduct1, setActiveProduct1] = useState(9);
Poprawione użyłem 0

2023-09-21 00:54 UTC, matwjablonski commented on src/components/features/Promoted/Promoted.js
> +  const [activeProduct1, setActiveProduct1] = useState(9);
nie chodziło o to żeby zmienić liczbę, tylko żeby ją opisać

jak wrócisz do swojego kodu za kilka dni to nie będziesz pamiętał dlaczego wziąłeś 10 produkt a nie 1 - co więcej może nie być aż 10 produktów, trzeba to przewidzieć

2023-09-21 00:56 UTC, matwjablonski requested changes

2023-09-21 00:56 UTC, matwjablonski commented on src/components/features/Promoted/Promoted.js
> +            ''
dlaczego pusty string? lepiej null

2023-09-21 05:04 UTC, karollion commented on src/components/features/Promoted/Promoted.js
> +            ''
Poprawione

2023-09-21 05:04 UTC, karollion commented on src/components/features/Promoted/Promoted.js
> +  const [activeProduct1, setActiveProduct1] = useState(9);
Dałem komentarz wyjaśniający

2023-09-21 05:59 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-21 06:54 UTC, Justek9 approved these changes

2023-09-22 08:08 UTC, matwjablonski approved these changes

2023-09-22 08:08 UTC, merged