Feature/WDP230901 34 component feedback functional
matwjablonski/wdp-2309-01 pull request #46
Opened 2023-09-20 17:32 UTC by karollion

https://projects.kodilla.com/browse/WDP230901-34

- zrobiłem funkcje do przesuwania w lewo i prawo
- dodałem Swipable
- dodałem poprawki zgłoszone w poprzednim pullrequescie do tego zadania

2023-09-20 18:07 UTC, Justek9 submitted a review, later dismissed
zmiana komentarzy ładnie działa

2023-09-20 19:00 UTC, matwjablonski requested changes

2023-09-20 19:00 UTC, matwjablonski commented on src/components/features/Feedback/Feedback.js
> +        <p
<p> semantycznie tutaj nie pasuje, lepszy byłby button (bo kojarzony jest z jakąś akcją)

2023-09-20 19:00 UTC, matwjablonski commented on src/components/features/Feedback/Feedback.js
> +      <li key={i}>
normalnie iterator jako key to zły pomysł, tutaj można to ewentualnie zaakceptować

2023-09-20 20:09 UTC, karollion commented on src/components/features/Feedback/Feedback.js
> +      <li key={i}>
Poprawione

2023-09-20 20:10 UTC, karollion commented on src/components/features/Feedback/Feedback.js
> +        <p
Poprawione

2023-09-20 20:18 UTC, Justek9 approved these changes

2023-09-21 00:57 UTC, matwjablonski approved these changes

2023-09-21 00:57 UTC, merged