WDP230901-28_Add functionality to gallery
matwjablonski/wdp-2309-01 pull request #50
Opened 2023-09-22 20:52 UTC by wierza

https://projects.kodilla.com/browse/WDP230901-28

- dodałem funkcjonalność do galerii

2023-09-22 21:28 UTC, Viktoryia-Vysotskaya submitted a review, later dismissed

2023-09-23 00:18 UTC, matwjablonski requested changes

2023-09-23 00:18 UTC, matwjablonski commented on src/components/features/Gallery/GallerySlider.js
> +  // eslint-disable-next-line no-unused-vars
dlaczego?

2023-09-23 00:18 UTC, matwjablonski commented on src/components/features/Gallery/GallerySlider.js
> +  // eslint-disable-next-line no-unused-vars
po co go zapisywać do stanu, skoro z niego nie korzystasz? myślę o  `selectedThumbnailIndex `

2023-09-23 06:08 UTC, karollion submitted a review, later dismissed
Działa tak jak opisano w zadaniu :)

2023-09-23 08:28 UTC, Justek9 approved these changes

2023-09-23 09:17 UTC, Justek9 approved these changes

2023-09-23 10:01 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-23 16:58 UTC, karollion approved these changes

2023-09-24 11:31 UTC, merged