WDP230901-36_Add SearchPage
matwjablonski/wdp-2309-01 pull request #52
Opened 2023-09-23 15:41 UTC by wierza

- https://projects.kodilla.com/browse/WDP230901-36

- dodałem SearchPage
- wyrenderowałem na sztywno przykładowe produkty z kategorii chair
- ustawiłem pobieranie wyszukiwanej nazwy z adresu url i wyświetlenie na stronie

2023-09-23 17:23 UTC, karollion requested changes
wszystkie napisy sie porozjezdzały na stronie i mają inne kolory

2023-09-23 18:28 UTC, wierza commented
> wszystkie napisy sie porozjezdzały na stronie i mają inne kolory

Trzeba do adresu strony dodać /search/chair Tam jest strona z wynikami

2023-09-23 19:19 UTC, karollion requested changes

2023-09-23 19:19 UTC, karollion commented on src/components/views/SearchPage/SearchPage.module.scss
> +.root {
Obejmij proszę rootem wszystkie klasy

2023-09-23 19:29 UTC, Justek9 submitted a review, later dismissed

2023-09-23 19:36 UTC, Justek9 approved these changes

2023-09-23 19:37 UTC, karollion approved these changes

2023-09-23 19:39 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-24 08:18 UTC, Justek9 approved these changes
jak dla mnie wszystko ładnie działa :)

2023-09-24 08:19 UTC, Viktoryia-Vysotskaya approved these changes

2023-09-24 09:55 UTC, karollion approved these changes

2023-09-24 11:33 UTC, merged